language: node_js
node_js: v9.5.0
git:
    depth: 1
    submodules: false
env:
    - STG_HOSTNAME=$(jq -r '.host.staging.hostname // .host.hostname' package.json) PROD_HOSTNAME=$(jq -r '.host.production.hostname // .host.hostname' package.json)
install:
    - yarn install
# script:
    # - yarn build:prod
before_deploy:
    - ssh-keyscan -H $STG_HOSTNAME >> ~/.ssh/known_hosts
    - ssh-keyscan -H $PROD_HOSTNAME >> ~/.ssh/known_hosts
    - openssl aes-256-cbc -K $encrypted_21dfeea756f6_key -iv $encrypted_21dfeea756f6_iv -in ssl/travis-ci.enc -out travis-ci -d
    - eval "$(ssh-agent -s)"
    - chmod 0400 travis-ci
    - ssh-add travis-ci
deploy:
    - provider: script
      script: sh $TRAVIS_BUILD_DIR/config/deploy-stg.sh
      skip_cleanup: true
      on:
        branch: master
        tags: false
    - provider: script
      script: sh $TRAVIS_BUILD_DIR/config/deploy-prod.sh
      skip_cleanup: true
      on:
        branch: master
        tags: true
        condition: "$TRAVIS_TAG != *manual*"
notifications:
    email:
        recipients: damiano.barbati@gmail.com
        on_success: always
        on_failure: always